name: Deploy Jobs Test

on:
  pull_request:
    types:
      - closed
    branches:
      - DEV
      - STG
      - PRD

jobs:
  build:
    # Check if PR was closed due to a merge.
    if: github.event.pull_request.merged == true
    # Create a job on Ubuntu 18.04
    name: Build & Deploy!
    runs-on: ubuntu-18.04
    steps:
      - name: branch-name-from
        run: echo ${{github.event.pull_request.head.ref}}
      - name: branch-name-to
        run: echo ${{github.ref}}
      # Copy github repo with submodules
      - name: clone-repo
        uses: actions/checkout@v1
        with:
          submodules: true
      # Install python
      - name: install-python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      # Install python dependencies
      - name: install-dependencies
        run: python -m pip install fire==0.3.1
      # DEPLOY DEV
      - name: deploy-dev
        if: github.ref == 'DEV'
        env:
          DATABRICKS_GITHUB_FROM_BRANCH: ${{github.event.pull_request.head.ref}}
          DATABRICKS_ENV: "DEV"
        run: python deploy-jobs.py sync_pull_request --commit-tag 'Merge pull request' --pretty-print
      # DEPLOY STG
      - name: deploy-stg
        if: github.ref == 'STG'
          if: github.event.pull_request.head.ref == 'DEV'
            env:
              DATABRICKS_GITHUB_FROM_BRANCH: ${{github.event.pull_request.head.ref}}
              DATABRICKS_ENV: "STG"
            run: python deploy.py display-env DATABRICKS_GITHUB_FROM_BRANCH
          if: github.event.pull_request.head.ref != 'DEV'
            env:
              DATABRICKS_GITHUB_FROM_BRANCH: ${{github.event.pull_request.head.ref}}
              DATABRICKS_ENV: "STG"
            run: python deploy.py display-env DATABRICKS_GITHUB_FROM_BRANCH
      # DEPLOY PRD
      - name: deploy-prd
        if: github.ref == 'PRD'
          if: github.event.pull_request.head.ref == 'STG'
            env:
              DATABRICKS_GITHUB_FROM_BRANCH: ${{github.event.pull_request.head.ref}}
              DATABRICKS_ENV: "PRD"
            run: python deploy.py display-env DATABRICKS_GITHUB_FROM_BRANCH
          if: github.event.pull_request.head.ref != 'STG'
            env:
              DATABRICKS_GITHUB_FROM_BRANCH: ${{github.event.pull_request.head.ref}}
              DATABRICKS_ENV: "PRD"
            run: python deploy.py display-env DATABRICKS_GITHUB_FROM_BRANCH

