name: File checker

on:
  pull_request:
    paths:
      - files/**

jobs:
  build:
    name: File Checker
    runs-on: ubuntu-20.04

    steps:
      # Copy github repo with submodules
      - name: clone-repo
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      # Install python
      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
      # Execute the json specification check command
      - name: file-checker
        run: python checker.py json_checker --filepath files
