name: Show SQL files

on:
  pull_request:
    branches:
      - PRD

jobs:
  build:
    name: show-sql-files
    runs-on: ubuntu-20.04
    steps:
      - name: clone-repo
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: changed-files
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          output_renamed_files_as_deleted_and_added: "true"
          files: this/is/a/**/*.sql
      - name: show-files
        run: >
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do echo "$file"; done
